alias ls='ls --color=auto'
alias ll='ls -l'
alias grep='grep --color=auto'
alias v='vim'
alias sv='sudo vim'
alias aptin='sudo apt install'
alias aptrm='sudo apt remove'
alias aptup='sudo apt update && sudo apt upgrade'
alias ..='cd ..'
alias ...='cd ../..'
