#!/bin/sh

#------------------------------------------------------------------AUTOSTART
sh ~/.fehbg 
sh ~/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr
picom --config ~/.config/picom/picom.conf &
xrdb ~/.Xresources
pkill dunst
dunst &
pgrep -x sxhkd > /dev/null || sxhkd &

#------------------------------------------------------------------GLOBAL
bspc config automatic_scheme manual
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#------------------------------------------------------------------COLORS
bspc config normal_border_color	"#1e1e1e"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#e2a478"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"

#------------------------------------------------------------------DESKTOP
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 3
bspc config window_gap 10
bspc config window_gap 12

#-----------------------------------------------------------------WORKSPACES
bspc monitor -d I II III IV V VI 

#----------------------------------------------------------------WINDOW RULES
bspc rule -a 'Pcmanfm' state=floating
bspc rule -a 'Sxiv' state=floating 
bspc rule -a 'Firefox:Toolkit' sticky=on state=floating
bspc rule -a 'Firefox:Browser' state=floating
