#!/bin/sh

# AUTOSTART
~/.fehbg 
killall polybar ; ~/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr
killall picom ; picom --experimental-backends --config ~/.config/picom/picom.conf &
xrdb ~/.Xresources
killall dunst ; dunst &
pgrep -x sxhkd > /dev/null || sxhkd &

# SETTINGS
bspc config focus_follows_pointer true
bspc config split_ratio           0.52
bspc config gapless_monocle	  true
bspc config borderless_monocle	  true

# COLORS
bspc config normal_border_color	"#1e1e1e"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"

# GAPS
bspc config top_padding 20
bspc config border_width 2
bspc config window_gap 10

# WORKSPACES
bspc monitor -d I II III IV V VI 

# WINDOW RULES
bspc rule -a 'Pcmanfm' state=floating
bspc rule -a 'Sxiv' state=floating 
bspc rule -a 'firefox:Toolkit' sticky=on state=floating
bspc rule -a 'firefox:Browser' state=floating
bspc rule -a 'mpv' state=floating
bspc rule -a 'discord' state=floating
bspc rule -a 'File-roller' state=floating
