#!/bin/sh

# AUTOSTART
[ -f ~/.xprofile ] && . ~/.xprofile
xsetroot -cursor_name left_ptr
~/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
dunst &

# SETTINGS
bspc config focus_follows_pointer true
bspc config split_ratio           0.51
bspc config gapless_monocle	  true
bspc config borderless_monocle	  true
bspc config pointer_motion_interval 16

# COLORS
bspc config normal_border_color	"#1e1e1e"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#D0D0D0"
bspc config presel_feedback_color "#327bd1"
bspc config urgent_border_color "#dd2727"

# GAPS
bspc config top_padding 25
bspc config border_width 3
bspc config window_gap 15

# WORKSPACES
bspc monitor -d 1 2 3 4 5

# WINDOW RULES
bspc rule -a 'Pcmanfm' state=floating
bspc rule -a 'Sxiv' state=floating 
bspc rule -a 'Firefox-esr:Toolkit' sticky=on state=floating
bspc rule -a 'Firefox-esr:Browser' state=floating
bspc rule -a 'mpv' state=floating
